import { createHash } from 'node:crypto';
import { spawn, spawnSync, type ChildProcessWithoutNullStreams } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import {
  digestTree,
  loadWorldLabConfig,
  SESSION_LOCK,
  TREE_DIGEST_PROFILE,
  type WorldLabDefinition,
} from './world-lab';
import { isMinecraftReadyLine, isMinecraftSaveAcknowledgement } from './world-runner';
import { verifyAdmittedPlaceEpoch } from './place-epoch';

export const OWNED_WORLD_ID = 'behold-owned-flat-v1';
export const OWNED_LEVEL_SEED = '424242';
export type OwnedWorldTarget = Readonly<{
  x: number;
  y: number;
  z: number;
  item: string;
  count: number;
}>;
export type OwnedWorldPoint = Readonly<{ x: number; y: number; z: number }>;
export type OwnedWorldBlock = Readonly<{
  x: number;
  y: number;
  z: number;
  block: string;
}>;
export const OWNED_TARGET: OwnedWorldTarget = Object.freeze({
  x: 3,
  y: -60,
  z: 0,
  item: 'apple',
  count: 1,
});

export async function prepareOwnedWorld(
  runIdValue: string,
  port: number,
  label = 'owned-world',
  target: OwnedWorldTarget = OWNED_TARGET,
  additionalTargets: readonly OwnedWorldTarget[] = [],
  preparedBlocks: readonly OwnedWorldBlock[] = [],
) {
  assertCleanRepository();
  const runId = safeSegment(runIdValue);
  if (!Number.isSafeInteger(port) || port < 1024 || port > 65535) {
    throw new Error(`invalid proof port: ${port}`);
  }
  const targets = Object.freeze(
    [target, ...additionalTargets].map((entry) => Object.freeze({ ...entry })),
  );
  for (const entry of targets) assertOwnedWorldTarget(entry);
  const blocks = Object.freeze(preparedBlocks.map((entry) => Object.freeze({ ...entry })));
  for (const entry of blocks) assertOwnedWorldBlock(entry);
  if (new Set(targets.map((entry) => `${entry.x},${entry.y},${entry.z}`)).size !== targets.length) {
    throw new Error('prepared proof targets must occupy distinct coordinates');
  }
  const occupied = [...targets, ...blocks].map((entry) => `${entry.x},${entry.y},${entry.z}`);
  if (new Set(occupied).size !== occupied.length) {
    throw new Error('prepared proof items and blocks must occupy distinct coordinates');
  }
  await assertPortAvailable(port);

  const repository = process.cwd();
  const root = path.resolve('.behold-runtime', 'owned-world-proofs', runId);
  if (fs.existsSync(root)) throw new Error(`proof run already exists: ${root}`);
  const serverDirectory = path.join(root, 'server');
  const runtime = path.join(serverDirectory, 'world');
  const source = path.join(root, 'source');
  const baseline = path.join(root, 'baseline');
  const archiveRoot = path.join(root, 'archive');
  const entityRoot = path.join(root, 'entities');
  const controlRoot = path.join(root, 'control');
  const evidenceRoot = path.join(root, 'evidence');
  for (const directory of [serverDirectory, archiveRoot, entityRoot, controlRoot, evidenceRoot]) {
    fs.mkdirSync(directory, { recursive: true });
  }

  const toolLock = JSON.parse(fs.readFileSync('docs/sf-world/tool-lock.json', 'utf8'));
  const serverJar = path.resolve(String(toolLock.tools.minecraftServer.path));
  const expectedServerJarSha256 = String(toolLock.tools.minecraftServer.sha256);
  const actualServerJarSha256 = sha256File(serverJar);
  if (actualServerJarSha256 !== expectedServerJarSha256) {
    throw new Error(`pinned server jar digest mismatch: ${actualServerJarSha256}`);
  }
  const java = bundledJava();
  writeServerConfiguration(serverDirectory, port);

  const startedAt = new Date().toISOString();
  process.stdout.write(`[${label}] generating deterministic flat world in ${root}\n`);
  const generation = await generatePreparedWorld({
    java,
    serverJar,
    serverDirectory,
    transcriptFile: path.join(evidenceRoot, 'generation.log'),
    targets,
    blocks,
  });
  copyWorld(runtime, source);
  copyWorld(runtime, baseline);
  const sourceTree = digestTree(source);
  const baselineTree = digestTree(baseline);
  const initialRuntimeTree = digestTree(runtime);
  if (
    sourceTree.digest !== baselineTree.digest ||
    baselineTree.digest !== initialRuntimeTree.digest
  ) {
    throw new Error('captured source, baseline, and initial runtime are not identical');
  }

  const world: WorldLabDefinition = {
    label: 'Behold-owned deterministic flat proof world',
    source: {
      path: source,
      digestProfile: TREE_DIGEST_PROFILE,
      expectedDigest: sourceTree.digest,
    },
    preparedBaseline: {
      path: baseline,
      digestProfile: TREE_DIGEST_PROFILE,
      expectedDigest: baselineTree.digest,
    },
    runtime: { worldPath: runtime, archiveRoot },
    server: { host: '127.0.0.1', port },
    notes: [
      `Generated by Minecraft 1.21.4 with level seed ${OWNED_LEVEL_SEED}.`,
      ...targets.map(
        (entry) =>
          `One dropped ${entry.item} stack of ${entry.count} is prepared at ${entry.x},${entry.y},${entry.z}.`,
      ),
      ...blocks.map(
        (entry) => `One ${entry.block} block is prepared at ${entry.x},${entry.y},${entry.z}.`,
      ),
    ],
  };
  durableWriteJson(path.join(root, 'world-definition.json'), {
    schemaVersion: 2,
    worlds: { [OWNED_WORLD_ID]: world },
  });

  return {
    worldId: OWNED_WORLD_ID,
    placeEpoch: null,
    admissionRoot: null,
    admissionDescriptorFile: null,
    admissionDescriptorSha256: null,
    admittedRuntimeTree: null,
    runId,
    port,
    repository,
    root,
    serverDirectory,
    runtime,
    source,
    baseline,
    archiveRoot,
    entityRoot,
    controlRoot,
    evidenceRoot,
    toolLock,
    serverJar,
    expectedServerJarSha256,
    actualServerJarSha256,
    java,
    startedAt,
    generation,
    sourceTree,
    baselineTree,
    initialRuntimeTree,
    target,
    targets,
    blocks,
    world,
  };
}

export async function prepareAdmittedPlaceWorld(
  runIdValue: string,
  admittedRootValue: string,
  arrival: OwnedWorldPoint,
  target: OwnedWorldTarget,
) {
  assertCleanRepository();
  const runId = safeSegment(runIdValue);
  assertOwnedWorldPoint(arrival, 'arrival');
  assertOwnedWorldTarget(target);

  const admittedRoot = path.resolve(admittedRootValue);
  const placeEpoch = verifyAdmittedPlaceEpoch(admittedRoot);
  const config = loadWorldLabConfig(path.join(admittedRoot, 'world-definition.json'));
  const world = config.worlds[placeEpoch.worldId];
  if (!world) throw new Error('admitted Place epoch has no world definition');
  const port = world.server.port;
  await assertPortAvailable(port);

  const repository = process.cwd();
  const root = path.resolve('.behold-runtime', 'place-epoch-proofs', runId);
  if (fs.existsSync(root)) throw new Error(`proof run already exists: ${root}`);
  const entityRoot = path.join(root, 'entities');
  const controlRoot = path.join(root, 'control');
  const evidenceRoot = path.join(root, 'evidence');
  for (const directory of [entityRoot, controlRoot, evidenceRoot]) {
    fs.mkdirSync(directory, { recursive: true });
  }

  const toolLock = JSON.parse(fs.readFileSync('docs/sf-world/tool-lock.json', 'utf8'));
  const serverJar = path.resolve(String(toolLock.tools.minecraftServer.path));
  const expectedServerJarSha256 = String(toolLock.tools.minecraftServer.sha256);
  const actualServerJarSha256 = sha256File(serverJar);
  if (
    actualServerJarSha256 !== expectedServerJarSha256 ||
    actualServerJarSha256 !== placeEpoch.behold.serverJarSha256
  ) {
    throw new Error('admitted Place epoch and pinned Minecraft server JAR do not match');
  }

  const source = placeEpoch.paths.source;
  const baseline = placeEpoch.paths.baseline;
  const serverDirectory = placeEpoch.paths.serverDirectory;
  const runtime = placeEpoch.paths.runtime;
  const archiveRoot = placeEpoch.paths.archiveRoot;
  const sourceTree = digestTree(source);
  const baselineTree = digestTree(baseline);
  const admittedRuntimeTree = digestTree(runtime);
  if (
    sourceTree.digest !== placeEpoch.behold.sourceTree.digest ||
    baselineTree.digest !== placeEpoch.behold.baselineTree.digest ||
    admittedRuntimeTree.digest !== baselineTree.digest
  ) {
    throw new Error('admitted Place epoch drifted before continuity proof');
  }

  const java = bundledJava();
  const startedAt = new Date().toISOString();
  process.stdout.write(
    `[owned-world] preparing packaged Place epoch ${placeEpoch.worldId} in ${root}\n`,
  );
  const preparation = await prepareExistingWorld({
    java,
    serverJar,
    serverDirectory,
    transcriptFile: path.join(evidenceRoot, 'preparation.log'),
    arrival,
    target,
  });
  const initialRuntimeTree = digestTree(runtime);

  return {
    worldId: placeEpoch.worldId,
    placeEpoch,
    admissionRoot: admittedRoot,
    admissionDescriptorFile: path.join(admittedRoot, 'place-epoch.json'),
    admissionDescriptorSha256: sha256File(path.join(admittedRoot, 'place-epoch.json')),
    admittedRuntimeTree,
    runId,
    port,
    repository,
    root,
    serverDirectory,
    runtime,
    source,
    baseline,
    archiveRoot,
    entityRoot,
    controlRoot,
    evidenceRoot,
    toolLock,
    serverJar,
    expectedServerJarSha256,
    actualServerJarSha256,
    java,
    startedAt,
    generation: preparation,
    sourceTree,
    baselineTree,
    initialRuntimeTree,
    target,
    targets: Object.freeze([Object.freeze({ ...target })]),
    blocks: Object.freeze([]),
    world,
  };
}

async function prepareExistingWorld(input: {
  java: string;
  serverJar: string;
  serverDirectory: string;
  transcriptFile: string;
  arrival: OwnedWorldPoint;
  target: OwnedWorldTarget;
}) {
  const startedAt = Date.now();
  const child = spawn(
    input.java,
    ['-Xms512M', '-Xmx1G', '-jar', fs.realpathSync.native(input.serverJar), 'nogui'],
    { cwd: input.serverDirectory, stdio: ['pipe', 'pipe', 'pipe'] },
  );
  const lines: string[] = [];
  const attach = (stream: NodeJS.ReadableStream, sink: NodeJS.WritableStream) => {
    let remainder = '';
    stream.on('data', (chunk) => {
      const text = String(chunk);
      sink.write(text);
      const parts = `${remainder}${text}`.split(/\r?\n/);
      remainder = parts.pop() || '';
      lines.push(...parts);
    });
  };
  attach(child.stdout, process.stdout);
  attach(child.stderr, process.stderr);
  const exit = waitForExit(child);
  await Promise.race([
    waitFor(() => lines.some(isMinecraftReadyLine), 90_000, 'admitted server readiness'),
    exit.then((result) => {
      throw new Error(`admitted server exited before readiness: ${JSON.stringify(result)}`);
    }),
  ]);
  for (const command of [
    'gamerule spawnRadius 0',
    `setworldspawn ${input.arrival.x} ${input.arrival.y} ${input.arrival.z}`,
    `kill @e[type=minecraft:item,x=${input.target.x},y=${input.target.y},z=${input.target.z},distance=..8]`,
    `summon minecraft:item ${input.target.x} ${input.target.y} ${input.target.z} {Item:{id:"minecraft:${input.target.item}",count:${input.target.count}}}`,
  ]) {
    child.stdin.write(`${command}\n`);
  }
  await waitFor(
    () => lines.some((line) => /Summoned new /.test(line)),
    30_000,
    'admitted item affordance',
  );
  child.stdin.write('save-all flush\n');
  await waitFor(
    () => lines.some(isMinecraftSaveAcknowledgement),
    30_000,
    'admitted world save acknowledgement',
  );
  child.stdin.write('stop\n');
  child.stdin.end();
  const result = await exit;
  if (result.code !== 0 || result.signal) {
    throw new Error(`admitted server stopped abnormally: ${JSON.stringify(result)}`);
  }
  fs.writeFileSync(input.transcriptFile, `${lines.join('\n')}\n`, 'utf8');
  return { durationMs: Date.now() - startedAt, exit: result, transcriptFile: input.transcriptFile };
}

async function generatePreparedWorld(input: {
  java: string;
  serverJar: string;
  serverDirectory: string;
  transcriptFile: string;
  targets: readonly OwnedWorldTarget[];
  blocks: readonly OwnedWorldBlock[];
}) {
  const startedAt = Date.now();
  const child = spawn(
    input.java,
    ['-Xms512M', '-Xmx1G', '-jar', fs.realpathSync.native(input.serverJar), 'nogui'],
    { cwd: input.serverDirectory, stdio: ['pipe', 'pipe', 'pipe'] },
  );
  const lines: string[] = [];
  const attach = (stream: NodeJS.ReadableStream, sink: NodeJS.WritableStream) => {
    let remainder = '';
    stream.on('data', (chunk) => {
      const text = String(chunk);
      sink.write(text);
      const parts = `${remainder}${text}`.split(/\r?\n/);
      remainder = parts.pop() || '';
      lines.push(...parts);
    });
  };
  attach(child.stdout, process.stdout);
  attach(child.stderr, process.stderr);
  const exit = waitForExit(child);
  await Promise.race([
    waitFor(() => lines.some(isMinecraftReadyLine), 90_000, 'generated server readiness'),
    exit.then((result) => {
      throw new Error(`generated server exited before readiness: ${JSON.stringify(result)}`);
    }),
  ]);
  for (const command of [
    'gamerule spawnRadius 0',
    'gamerule doDaylightCycle false',
    'time set day',
    'weather clear',
    'setworldspawn 0 -60 0',
    ...input.targets.map(
      (target) =>
        `summon minecraft:item ${target.x} ${target.y} ${target.z} {Item:{id:"minecraft:${target.item}",count:${target.count}}}`,
    ),
    ...input.blocks.map(
      (block) => `setblock ${block.x} ${block.y} ${block.z} minecraft:${block.block}`,
    ),
  ]) {
    child.stdin.write(`${command}\n`);
  }
  await waitFor(
    () => lines.filter((line) => /Summoned new /.test(line)).length >= input.targets.length,
    30_000,
    'generated item affordance',
  );
  await waitFor(
    () => lines.filter((line) => /Changed the block at /.test(line)).length >= input.blocks.length,
    30_000,
    'generated prepared blocks',
  );
  child.stdin.write('save-all flush\n');
  await waitFor(
    () => lines.some(isMinecraftSaveAcknowledgement),
    30_000,
    'generated world save acknowledgement',
  );
  child.stdin.write('stop\n');
  child.stdin.end();
  const result = await exit;
  if (result.code !== 0 || result.signal) {
    throw new Error(`generated server stopped abnormally: ${JSON.stringify(result)}`);
  }
  fs.writeFileSync(input.transcriptFile, `${lines.join('\n')}\n`, 'utf8');
  return { durationMs: Date.now() - startedAt, exit: result, transcriptFile: input.transcriptFile };
}

function writeServerConfiguration(directory: string, port: number) {
  const properties = [
    'allow-flight=true',
    'difficulty=peaceful',
    'enable-command-block=false',
    'enable-rcon=false',
    'enforce-secure-profile=false',
    'force-gamemode=true',
    'function-permission-level=2',
    'gamemode=survival',
    'generate-structures=false',
    `level-seed=${OWNED_LEVEL_SEED}`,
    'level-type=minecraft:flat',
    'max-players=4',
    'motd=Behold owned-world proof',
    'online-mode=false',
    'player-idle-timeout=0',
    'prevent-proxy-connections=false',
    'pvp=false',
    'server-ip=127.0.0.1',
    `server-port=${port}`,
    'simulation-distance=4',
    'spawn-animals=false',
    'spawn-monsters=false',
    'spawn-npcs=false',
    'spawn-protection=0',
    'sync-chunk-writes=true',
    'view-distance=4',
    'white-list=false',
  ];
  fs.writeFileSync(path.join(directory, 'eula.txt'), 'eula=true\n', 'utf8');
  fs.writeFileSync(path.join(directory, 'server.properties'), `${properties.join('\n')}\n`, 'utf8');
}

function copyWorld(from: string, to: string) {
  fs.cpSync(from, to, {
    recursive: true,
    force: false,
    errorOnExist: true,
    preserveTimestamps: true,
    filter: (entry) => path.relative(from, entry) !== SESSION_LOCK,
  });
}

export function waitFor(
  condition: () => boolean,
  timeoutMs: number,
  label: string,
  signal?: AbortSignal,
) {
  return waitForAsync(condition, timeoutMs, label, signal);
}

async function waitForAsync(
  condition: () => boolean,
  timeoutMs: number,
  label: string,
  signal?: AbortSignal,
) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    signal?.throwIfAborted();
    if (condition()) return;
    await abortableDelay(100, signal);
  }
  throw new Error(`${label} timed out after ${timeoutMs}ms`);
}

function abortableDelay(milliseconds: number, signal?: AbortSignal) {
  if (!signal) return new Promise<void>((resolve) => setTimeout(resolve, milliseconds));
  signal.throwIfAborted();
  return new Promise<void>((resolve, reject) => {
    const timer = setTimeout(() => {
      signal.removeEventListener('abort', onAbort);
      resolve();
    }, milliseconds);
    const onAbort = () => {
      clearTimeout(timer);
      reject(signal.reason);
    };
    signal.addEventListener('abort', onAbort, { once: true });
  });
}

function waitForExit(child: ChildProcessWithoutNullStreams) {
  return new Promise<{ code: number | null; signal: NodeJS.Signals | null }>((resolve, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) => resolve({ code, signal }));
  });
}

function assertPortAvailable(port: number) {
  return new Promise<void>((resolve, reject) => {
    const server = net.createServer();
    server.once('error', reject);
    server.listen(port, '127.0.0.1', () =>
      server.close((error) => (error ? reject(error) : resolve())),
    );
  });
}

export function assertCleanRepository() {
  const status = spawnSync('git', ['status', '--porcelain=v1', '--untracked-files=all'], {
    encoding: 'utf8',
  });
  if (status.status !== 0 || String(status.stdout).length > 0) {
    throw new Error('owned-world proof requires a clean Git worktree');
  }
}

export function gitRevision() {
  const result = spawnSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' });
  if (result.status !== 0) throw new Error('could not resolve Git revision');
  return String(result.stdout).trim();
}

function bundledJava() {
  const candidate = path.join(
    os.homedir(),
    'Library',
    'Application Support',
    'minecraft',
    'runtime',
    'java-runtime-delta',
    'mac-os-arm64',
    'java-runtime-delta',
    'jre.bundle',
    'Contents',
    'Home',
    'bin',
    'java',
  );
  const java = process.env.SERVER_JAVA || (fs.existsSync(candidate) ? candidate : 'java');
  const version = spawnSync(java, ['-version'], { encoding: 'utf8' });
  if (version.status !== 0) throw new Error(`Java is unavailable: ${version.stderr}`);
  return java;
}

export function sha256File(file: string) {
  return createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

export function readJson(file: string) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

export function listFiles(directory: string): string[] {
  if (!fs.existsSync(directory)) return [];
  return fs
    .readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const full = path.join(directory, entry.name);
      return entry.isDirectory() ? listFiles(full) : [full];
    })
    .sort();
}

export function durableWriteJson(file: string, value: unknown) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temporary = `${file}.${process.pid}.tmp`;
  const descriptor = fs.openSync(temporary, 'wx', 0o600);
  try {
    fs.writeFileSync(descriptor, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
    fs.fsyncSync(descriptor);
  } finally {
    fs.closeSync(descriptor);
  }
  fs.renameSync(temporary, file);
  const parent = fs.openSync(path.dirname(file), 'r');
  try {
    fs.fsyncSync(parent);
  } finally {
    fs.closeSync(parent);
  }
}

function safeSegment(value: string) {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(value)) throw new Error(`unsafe run id: ${value}`);
  return value;
}

function assertOwnedWorldTarget(target: OwnedWorldTarget) {
  assertOwnedWorldPoint(target, 'target');
  if (!/^[a-z0-9_]+$/.test(target.item)) {
    throw new Error(`owned-world target has an invalid Minecraft item name: ${target.item}`);
  }
  if (!Number.isSafeInteger(target.count) || target.count < 1 || target.count > 64) {
    throw new Error(`owned-world target count must be an integer from 1 to 64: ${target.count}`);
  }
}

function assertOwnedWorldPoint(point: OwnedWorldPoint, label: string) {
  if (![point.x, point.y, point.z].every(Number.isSafeInteger)) {
    throw new Error(`owned-world ${label} requires integer coordinates: ${JSON.stringify(point)}`);
  }
}

function assertOwnedWorldBlock(block: OwnedWorldBlock) {
  if (![block.x, block.y, block.z].every(Number.isSafeInteger)) {
    throw new Error(`owned-world block requires integer coordinates: ${JSON.stringify(block)}`);
  }
  if (!/^[a-z0-9_]+$/.test(block.block)) {
    throw new Error(`owned-world block has an invalid Minecraft block name: ${block.block}`);
  }
}

export function restoreEnvironment(name: string, value: string | undefined) {
  if (value === undefined) delete process.env[name];
  else process.env[name] = value;
}
